mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 123

  mail:
    host: smtp.qq.com
    username: 787492833@qq.com
    password: ayuoijnfponsbebi

logging:
  level:
    root: warn
    com.imooc.mapper: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
